### ISSUE TITLE
How to calculate age

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#14]
Before I forget again, since I keep forgetting: what to do with runners whose birthday next year would have them switch teams? e.g. runner turns 30 on July 1, 2021: do they go in the 20s or 30s?

_Originally posted by @stevedesmond-ca in https://github.com/FingerLakesRunnersClub/ChallengeDashboard/issues/10#issuecomment-734891511_

**Comment by adamengst** [comment]
So, this is a bit of a question, and I'm open to ideas. My initial idea was to ask for the runner's age as of January 1st, 2021, and to keep them in that team for the entirety of the year. That's roughly how PGXC does things.

But that does open up the question of how to decide what age a person is with regard to per-race age-group results. For that, I'd suggest that it should be your age as of the actual effort. So someone could actually compete in two age groups for the same race, if they changed age groups during the year, which seems fair in this context. 

For that, we'd need birthdate, but I can ask for that, and Webscorer can calculate age as of a specific date, such as January 1st. So does that all make sense?

<img width="636" alt="Screen Shot 2020-11-28 at 12 19 35 PM" src="https://user-images.githubusercontent.com/36641103/100521830-16989d80-3174-11eb-9854-3938bc350aec.png">

**Comment by stevedesmond-ca** [comment]
I'm not currently seeing DOB coming through on the API responses, my guess is for privacy reasons, so it may be a little more complicated to do both the consistent year-long age (for teams) as well as the "as of the effort" age.

There is a "year of birth" field, which if filled out we could use for the team age (since we can determine age as of Jan 1 from that), with the "as of effort" age coming through via the WebScorer-calculated "Age" field.

@adamengst Do you have a test race set up with the QR code etc. so we can confirm how things like this and multiple efforts are coming through?

**Comment by adamengst** [comment]
Good question. It will be easier to ask Vesa than to test—more in email....

**Comment by adamengst** [comment]
Oh, sorry, forgot to mention it here. Test details at:

https://forum.fingerlakesrunners.org/t/qr-code-test-1-race-now-available-for-testing-and-importing/1592?u=adamengst

**Comment by stevedesmond-ca** [comment]
Ack, my bad, apparently I'm not getting forum notifications, I'll have to check my settings.

**Comment by stevedesmond-ca** [comment]
Teams are being auto-assigned based on the age coming from Web Scorer, but the "winning multiple age groups" part is still blocked the DOB not coming through in the API results.

**Comment by stevedesmond-ca** [comment]
DOB is now coming through via the API, moving conversation about how to display "as of effort" ages to #19
