### ISSUE TITLE
Overall page showing age-grade averages for best effort across all races

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#15]
Realized I forgot this one. As a competitive age-group runner, I'd like to feel like I have a stake in the overall Challenge competition, so I want to see how my average age-grading for each of my best efforts across all the courses positions me against all other competitors. The age-grading will eliminate age and gender differences, in theory.

Acceptance criteria:
* The page should show a list of all runners who have completed all 10 courses in Challenge, showing rank, name, age, and average age-grading.
* The list should be sorted by average age-grading, with the largest number at the top, but be sortable by clicking column headers (click once to sort, click a second time to reverse sort).

For the purposes of calculation, we'd take the age-grade number for just each runner's best effort on every course, and average them together. That way there's no penalty for running slowly.

**Comment by stevedesmond-ca** [comment]
Should this have a top 3 on the front page as well?

**Comment by stevedesmond-ca** [comment]
I was thinking about the "trail factor" you mentioned the other day regarding compensating for the seemingly low age grade percentages on harder trail courses, and realized that that would have the side effect of weighting those courses heavier for this overall competition.

If we want to scale certain courses' "importance" up or down based on this weighting factor, that would be a way to do it, but if the goal is to have each of the 10 courses count equally, then we'll have to keep the age grades for all the courses using the same standards.

**Comment by adamengst** [comment]
Good question about it having a top 3 on the front page as well, and let's see what @scottpdawson thinks. Right now we have four top 3 boxes, and this would make it five, which could either help or hinder the layout on a big screen.

The main argument for NOT having it on the front page is that the age-grade average isn't currently a prize-based competition. It's just because we have the data and it gives runners a sense of how they compare against each other once age and gender are taken out.

As far as the age-grading weighting the courses one way or another, I see what you're saying, but doesn't it go both ways? In other words, right now, the flat, fast courses are weighted more heavily than the hilly trail courses by virtue of getting higher age grades.

**Comment by stevedesmond-ca** [comment]
Unless we add some sort of indicator (:medal_sports:) for which competitions receive awards, I agree that it might be confusing/frustrating to either need to remember which is award-worthy, or assume that it is because it's on the leaderboard and focus on winning that and get to the end and only have bragging rights to show for it.

**Comment by stevedesmond-ca** [comment]
Pushing the weighting idea to an extreme, if we gave Thom B (for example) a factor of 100x, no other courses ends up mattering at all -- whoever has the best Thom B age grade wins the whole thing. Decreasing to a factor of 5x, chances are you can tank all the others but if you win Thom B, you'll still be in the lead overall. With a factor of 1.5x-2x it's less obvious, but the principle remains: any formula we use to manipulate one course needs to be used for all of them.

Some number:

If the competition had 3 courses, we could represent the overall average age grade using `(1 * AG1 + 1 * AG2 + 1 * AG3) / 3`
Athlete1 gets `(90 + 90 + 30) / 3 = 70` and Athlete2 `(85 + 85 + 36) / 3 = 68.7` so Athlete1 wins.

Changing that to `(1 * AG1 + 1 * AG2 + 2 * AG3) / 3` (scaling AG3 x2 so the low numbers look better) and suddenly it's no longer an average -- Athlete1 gets `(90 + 90 + 2*30) / 3 = 80` and Athlete2 gets `(85 + 85 + 2*36) / 3 = 80.7` and now Athlete2 wins because they were faster on the weighted course.

Sorry for all the math, trying to clarify for myself as much as anything :sweat_smile: -- I think the bottom line comes down to "age grade is a very specific value" and if we want to have a competition based on age grade, we need to use age grade. UltraSignup has their own "Rank %" (closer to our "Points") instead of age grade because the difficulty and variance in trail courses means there's not much basis for age grade comparisons on trails.

We can use something else for the overall competition, but it needs to be applied equally across all courses. We could figure out some calculation to "bell curve" the age grades into "Age Grade Points" (just like we do for the current "Speed Points") that could be applied equally for all the courses -- that would be more fair/equitable, though admittedly more complex/confusing, but the overall competition would be on the same 0-1000 scale as "Overall Points" (which we'd probably need to rename).

**Comment by adamengst** [comment]
It's sounding like we should stick with the specific age grade value for now and see if it feels weird later on or generates confusion among runners.

And you know, the more I look at this, the more I think that just adding an average age-grade column to the Most Points Overall tables (and eliminating the need for it to list only those who've run all races) would address the issue more cleanly and without adding another page. Does that sound right to you?

**Comment by stevedesmond-ca** [comment]
Yeah, if there's no award for it, let's just go with that!

**Comment by adamengst** [comment]
Good—easier and more understandable, while still providing the data those of us who are only going to compete on the age-grading side will want. :-)

**Comment by stevedesmond-ca** [comment]
Implemented as of 82217e5
