### ISSUE TITLE
Calculating age-grades

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#8]
As an older competitor, I want to see age-grades for each result, and as the race director, I want to use the age-grading to get the teams compete on a fair playing field.

Acceptance criteria:
* For each result, an age-grade will be calculated.
* The age-grade calculation should be based on Alan Jones's tables at https://github.com/AlanLyttonJones/Age-Grade-Tables/tree/master/2020%20Files
* If it's relatively hard to calculate age-grades, we can find a distance that's roughly the average of our course distances, or else we can use individual distance age-grade results for the closest distance.

**Comment by stevedesmond-ca** [comment]
I'm not seeing any formulas in that GitHub repo, only hardcoded numbers for set distances, so I think we'll just need to pick an "age grade distance" for each of our courses

**Comment by adamengst** [comment]
Here's another calculator that provides an Excel sheet with percentages for every age and distance. That should work better!

http://www.howardgrubb.co.uk/athletics/mldrroad20.html

**Comment by stevedesmond-ca** [comment]
Did some more research, was hoping for a single function that could be used across the board, but it looks like the age factors are manually set (based off world records for that age?). Howard's spreadsheet was helpful to see how it's using the data from Alan's. So I'll just need to have the app parse Alan's on startup, and linear interpolate based on the distance.

**Comment by stevedesmond-ca** [comment]
This was open-sourced as a standalone library: https://github.com/FingerLakesRunnersClub/AgeGradeCalculator/

**Comment by adamengst** [comment]
Nice! Thanks for open-sourcing it....

**Comment by adamengst** [comment]
At some point, @stevedesmond-ca, could you clarify exactly how you're calculating the age grade for different distances so I can document it for the rules?

**Comment by stevedesmond-ca** [comment]
Sure -- the calculator library has encoded the "standard" times from Alan Jones' tables for each age 5-100 and each "standard" distance" (aka common race distance) on the road.

The age grade percent is the "standard time" (aka world best for that age) divided by the runners time. e.g. if 50yo M half-marathon standard was 1:20:00 (made up number for simplicity) and you ran 2:40:00, your age grade would be 50%. It basically says "how much of the race did you complete by the time the fastest run ever for your your age completed."

For "standard" distances (those in the tables), these values are calculated directly against the values from the table. For distances other than "standard distances", a linear interpolation is taken between the age grades of the closest distance above and below the actual race distance. e.g. Since there are 5km and 6km standard distances, if your race was 5.5km, the resulting age grade would be half-way between the 5K and 6K age grades, but if it were 5.25km, it would be weighted 75/25 towards the 5K standard time. This matches the way that other online age grade calculators do it.

Does that help?

**Comment by adamengst** [comment]
Yep, that's exactly what I need, I think. Part of what surprised me with some of the test races was that because they're trail races, the age grades are much lower than they would have been for a road race. For someone like me who's used to seeing age grades in the 70-90 range, seeing a winner come in at 40-something was unexpected. But of course it makes perfect sense because the trail is so much slower than the road. 

All that matters is that the numbers are consistent for everyone in a particular race. The overall numbers won't be intuitive the way they are for road/track, but oh well....

**Comment by stevedesmond-ca** [comment]
lol, yeah, that was the first thing I noticed as well, how low the trail results seemed, but I double checked on other age grade calculators to confirm!

I did look for trail standards to see if we could use them based on the course type, but my guess is there's just so much variance in what "trail" means to people (e.g. South Hill Rec Way vs FL50s) that it would be super inconsistent anyway

**Comment by adamengst** [comment]
I suppose that, after we have more data from the flat and road courses, we could come up with some multipliers to bring the age grades into the right ballpark. For instance, if we have someone like Sam Lagasse who hits 92% on several flat courses, we could build in a multiplier to ensure that his times on the trail courses work out to similar age grading. (Given that Sam has run 14:28 for 5K on the track, he's probably someone who could be counted on for a relatively consistent fast time.)
