### ISSUE TITLE
Figure out best way to maintain 2021 leaderboard access indefinitely

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#93]
As the race director, I want to ensure that we maintain access to the 2021 leaderboard indefinitely. There are two aspects of that:

* Architectural: Up to you, whether that means rendering to static pages or maintaining the links to Webscorer. (But what would happen if they change the API or we lose state due to a server move or the like and need to reload in the future?)
* URL: On the assumption that we'll want to use the main challenge.fingerlakesrunners.org URL for the 2022 Challenge, we'll need to figure out some way to rename this year's URLs. We could do it with a subdomain or a subdirectory—just let me know if you need me to fiddle DNS at all.

Happy to discuss these—I have no huge opinions about the right way to go.

**Comment by SteveDesmond-ca** [comment]
I scraped the whole app this afternoon, so if you could add a DNS `A` record for `*.challenge.fingerlakesrunners.org` pointing to the same IP address as the others, I can get a static version up on a new sub-subdomain in the next couple days.

**Comment by adamengst** [comment]
Thanks! I think I've got the DNS set up as you wanted. Perhaps a subdomain of 2021.challenge.fingerlakesrunners.org? Or is that too many levels, suggesting something more like 2021-challenge.fingerlakesrunners.org?

![image](https://user-images.githubusercontent.com/36641103/149824832-a2bb1698-7508-4e29-9587-a8ee709c352d.png)

**Comment by SteveDesmond-ca** [comment]
:100: I just confirmed that `2021.challenge.fingerlakesrunners.org` resolves correctly, so I'll get the static version up and running there at some point tomorrow.

**Comment by SteveDesmond-ca** [comment]
https://2021.challenge.fingerlakesrunners.org is now live -- I've also included a copy of the whole static site here, for archival purposes: [2021.zip](https://github.com/FingerLakesRunnersClub/ChallengeDashboard/files/7890001/2021.zip)

The following are known caveats that don't have an easy fix, but everything else looks good at first glance:
- the age group dropdown on the fastest per-course times list doesn't work, due to that filtering being implemented with query strings, which static sites can't understand
- the "Recent" tabs of all of the "Activity Log" pages are blank, since the site was scraped this past weekend and no runs happened in the prior 10 days

Technically, since the whole thing is just static HTML files, feel free to edit them manually, if you wanted to tweak either of the above -- they're in `/var/www/2021-challenge`, with the `2021.zip` stored there as a backup as well, just in case!

**Comment by adamengst** [comment]
Yeah, I noticed the Recent tabs weren't useful even on the live site yesterday too. I think this is fine for now; as you say, we could edit the static HTML to point the Activity Log buttons at the Archive tab rather than the Recent tab. I doubt most people will want to look at it in that detail. Thanks!
